const JSON = {
    "_dispatchInstances": {
        "_debugHookTypes": null, 
        "_debugNeedsRemount": false, 
        "_debugOwner": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 1, 
            "actualStartTime": 1657677116903, 
            "alternate": [FiberNode], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": [Object], 
            "flags": 1, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": [Object], 
            "return": [FiberNode], 
            "selfBaseDuration": 1, 
            "sibling": null, 
            "stateNode": null, 
            "subtreeFlags": 1048581, 
            "tag": 11, 
            "treeBaseDuration": 3, 
            "type": [Object], 
            "updateQueue": null
        }, 
        "_debugSource": {
            "columnNumber": 7, 
            "fileName": "/Users/jiwon/Documents/GitHub/common_test_app/node_modules/react-native/Libraries/Components/View/View.js", 
            "lineNumber": 32
        
        }, 
        "actualDuration": 0, 
        "actualStartTime": 1657677116904, 
        "alternate": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object],
            "actualDuration": 3,
            "actualStartTime": 1657677115395,
            "alternate": [Circular],
            "child": [FiberNode],
            "childLanes": 0,
            "deletions": null,
            "dependencies": null,
            "elementType": "RCTView",
            "flags": 4,
            "index": 0,
            "key": null,
            "lanes": 0,
            "memoizedProps": [Object],
            "memoizedState": null,
            "mode": 2,
            "pendingProps": [Object],
            "ref": [Object],
            "return": [FiberNode],
            "selfBaseDuration": 1,
            "sibling": null,
            "stateNode": [ReactNativeFiberHostComponent],
            "subtreeFlags": 1048581,
            "tag": 5,
            "treeBaseDuration": 3,
            "type": "RCTView",
            "updateQueue": null
        }, 
        "child": {
            "_debugHookTypes": [Array], 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 0, 
            "actualStartTime": 1657677116904, 
            "alternate": [FiberNode], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": [Object], 
            "elementType": [Object], 
            "flags": 1048576, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": [Object], 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": null, 
            "return": [Circular], 
            "selfBaseDuration": 2, 
            "sibling": [FiberNode], 
            "stateNode": null, 
            "subtreeFlags": 0, 
            "tag": 11, 
            "treeBaseDuration": 2, 
            "type": [Object], 
            "updateQueue": [Object]
        }, 
        "childLanes": 0, 
        "deletions": null, 
        "dependencies": null, 
        "elementType": "RCTView", 
        "flags": 4, 
        "index": 0, 
        "key": null, 
        "lanes": 0, 
        "memoizedProps": {
            "accessibilityState": undefined, 
            "accessible": true, 
            "children": [Array], 
            "collapsable": false, 
            "focusable": true, 
            "hitSlop": undefined, 
            "onBlur": [Function onBlur], 
            "onClick": [Function onClick], 
            "onFocus": [Function onFocus], 
            "onResponderGrant": [Function onResponderGrant], 
            "onResponderMove": [Function onResponderMove], 
            "onResponderRelease": [Function onResponderRelease], 
            "onResponderTerminate": [Function onResponderTerminate], 
            "onResponderTerminationRequest": [Function onResponderTerminationRequest], 
            "onStartShouldSetResponder": [Function onStartShouldSetResponder], 
            "style": [Object]
        }, 
        "memoizedState": null, 
        "mode": 2, 
        "pendingProps": {
            "accessibilityState": undefined, 
            "accessible": true, 
            "children": [Array], 
            "collapsable": false, 
            "focusable": true, 
            "hitSlop": undefined, 
            "onBlur": [Function onBlur], 
            "onClick": [Function onClick], 
            "onFocus": [Function onFocus], 
            "onResponderGrant": [Function onResponderGrant], 
            "onResponderMove": [Function onResponderMove], 
            "onResponderRelease": [Function onResponderRelease], 
            "onResponderTerminate": [Function onResponderTerminate], 
            "onResponderTerminationRequest": [Function onResponderTerminationRequest], 
            "onStartShouldSetResponder": [Function onStartShouldSetResponder], 
            "style": [Object]
        }, 
        "ref": {
            "current": [ReactNativeFiberHostComponent]
        }, 

        "return": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 0, 
            "actualStartTime": 1657677116904, 
            "alternate": [FiberNode], 
            "child": [Circular], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": [Object], 
            "flags": 0, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": null, 
            "return": [FiberNode], 
            "selfBaseDuration": 0, 
            "sibling": null, 
            "stateNode": null, 
            "subtreeFlags": 1048581, 
            "tag": 10, 
            "treeBaseDuration": 2, 
            "type": [Object], 
            "updateQueue": null
        }, 
        
        "selfBaseDuration": 0, 
        
        "sibling": null, 
        
        "stateNode": {
            "_children": [Array], 
            "_internalFiberInstanceHandleDEV": [Circular], 
            "_nativeTag": 7, 
            "viewConfig": [Object]
        }, 
        
        "subtreeFlags": 1048577, 
        "tag": 5, 
        "treeBaseDuration": 2, 
        "type": "RCTView", 
        "updateQueue": null
        }, 
        
        "_dispatchListeners": [Function onResponderRelease], 
        "_targetInst": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 1, 
            "actualStartTime": 1657677116903, 
            "alternate": [FiberNode], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": [Object], 
            "flags": 1, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": [Object], 
            "return": [FiberNode], 
            "selfBaseDuration": 1, 
            "sibling": null, 
            "stateNode": null, 
            "subtreeFlags": 1048581, 
            "tag": 11, 
            "treeBaseDuration": 3, 
            "type": [Object], 
            "updateQueue": null
        }, 
        
        "_debugSource": {
            "columnNumber": 7, 
            "fileName": "/Users/jiwon/Documents/GitHub/common_test_app/node_modules/react-native/Libraries/Components/View/View.js", 
            "lineNumber": 32
        }, 
        
        "actualDuration": 0, 
        "actualStartTime": 1657677116904, 
        "alternate": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 3, 
            "actualStartTime": 1657677115395, 
            "alternate": [Circular], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": "RCTView", 
            "flags": 4, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": [Object], 
            "return": [FiberNode], 
            "selfBaseDuration": 1, 
            "sibling": null, 
            "stateNode": [ReactNativeFiberHostComponent], 
            "subtreeFlags": 1048581, 
            "tag": 5, 
            "treeBaseDuration": 3, 
            "type": "RCTView", 
            "updateQueue": null
        }, 
        
        "child": {
            "_debugHookTypes": [Array], 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 0, 
            "actualStartTime": 1657677116904, 
            "alternate": [FiberNode], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": [Object], 
            "elementType": [Object], 
            "flags": 1048576, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": [Object], 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": null, 
            "return": [Circular], 
            "selfBaseDuration": 2, 
            "sibling": [FiberNode], 
            "stateNode": null, 
            "subtreeFlags": 0, 
            "tag": 11, 
            "treeBaseDuration": 2, 
            "type": [Object], 
            "updateQueue": [Object]
        }, 
        
        "childLanes": 0, 
        "deletions": null, 
        "dependencies": null, 
        "elementType": "RCTView", 
        "flags": 4, 
        "index": 0, 
        "key": null, 
        "lanes": 0, 
        "memoizedProps": {
            "accessibilityState": undefined, 
            "accessible": true, 
            "children": [Array], 
            "collapsable": false, 
            "focusable": true, 
            "hitSlop": undefined, 
            "onBlur": [Function onBlur], 
            "onClick": [Function onClick], 
            "onFocus": [Function onFocus], 
            "onResponderGrant": [Function onResponderGrant], 
            "onResponderMove": [Function onResponderMove], 
            "onResponderRelease": [Function onResponderRelease], 
            "onResponderTerminate": [Function onResponderTerminate], 
            "onResponderTerminationRequest": [Function onResponderTerminationRequest], 
            "onStartShouldSetResponder": [Function onStartShouldSetResponder], 
            "style": [Object]
        }, 
        
        "memoizedState": null, 
        "mode": 2, 
        "pendingProps": {
            "accessibilityState": undefined, 
            "accessible": true, 
            "children": [Array], 
            "collapsable": false, 
            "focusable": true, 
            "hitSlop": undefined, 
            "onBlur": [Function onBlur], 
            "onClick": [Function onClick], 
            "onFocus": [Function onFocus], 
            "onResponderGrant": [Function onResponderGrant], 
            "onResponderMove": [Function onResponderMove], 
            "onResponderRelease": [Function onResponderRelease], 
            "onResponderTerminate": [Function onResponderTerminate], 
            "onResponderTerminationRequest": [Function onResponderTerminationRequest], 
            "onStartShouldSetResponder": [Function onStartShouldSetResponder], 
            "style": [Object]
        }, 
        
        "ref": {
            "current": [ReactNativeFiberHostComponent]
        }, 
        
        "return": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 0, 
            "actualStartTime": 1657677116904, 
            "alternate": [FiberNode], 
            "child": [Circular], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": [Object], 
            "flags": 0, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": null, 
            "return": [FiberNode], 
            "selfBaseDuration": 0, 
            "sibling": null, 
            "stateNode": null, 
            "subtreeFlags": 1048581, 
            "tag": 10, 
            "treeBaseDuration": 2, 
            "type": [Object], 
            "updateQueue": null
        }, 
        
        "selfBaseDuration": 0, 
        "sibling": null, 
        "stateNode": {
            "_children": [Array], 
            "_internalFiberInstanceHandleDEV": [Circular], 
            "_nativeTag": 7, 
            "viewConfig": [Object]
        }, 
        
        "subtreeFlags": 1048577, 
        "tag": 5, 
        "treeBaseDuration": 2, 
        "type": "RCTView", 
        "updateQueue": null
        }, 
        
        "bubbles": undefined, 
        "cancelable": undefined, 
        "currentTarget": {
            "_children": [[ReactNativeFiberHostComponent]], 
            "_internalFiberInstanceHandleDEV": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 0, 
            "actualStartTime": 1657677116904, 
            "alternate": [FiberNode], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": "RCTView", 
            "flags": 4, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": [Object], 
            "return": [FiberNode], 
            "selfBaseDuration": 0, 
            "sibling": null, 
            "stateNode": [Circular], 
            "subtreeFlags": 1048577, 
            "tag": 5, 
            "treeBaseDuration": 2, 
            "type": "RCTView", 
            "updateQueue": null
        }, 
        
        "_nativeTag": 7, 
        "viewConfig": {
            "Commands": [Object], 
            "NativeProps": [Object], 
            "bubblingEventTypes": [Object], 
            "directEventTypes": [Object], 
            "uiViewClassName": "RCTView", 
            "validAttributes": [Object]
        }
        }, 
        
        "defaultPrevented": undefined, 
        "dispatchConfig": {
            "dependencies": ["topTouchCancel", 
            "topTouchEnd"], 
            "registrationName": "onResponderRelease"
        }, 
        
        "eventPhase": undefined, 
        "isDefaultPrevented": [Function functionThatReturnsFalse], 
        "isPersistent": [Function functionThatReturnsTrue], 
        "isPropagationStopped": [Function functionThatReturnsFalse], 
        "isTrusted": undefined, 
        "nativeEvent": {
            "changedTouches": [[Circular]], 
            "identifier": 0, 
            "locationX": 239.765625, 
            "locationY": 157.9287109375, 
            "pageX": 239.765625, 
            "pageY": 157.9287109375, 
            "target": 7, 
            "targetSurface": -1, 
            "timestamp": 47628960, 
            "touches": []
        }, 
        
        "target": {
            "_children": [[ReactNativeFiberHostComponent]], 
            "_internalFiberInstanceHandleDEV": {
            "_debugHookTypes": null, 
            "_debugNeedsRemount": false, 
            "_debugOwner": [FiberNode], 
            "_debugSource": [Object], 
            "actualDuration": 0, 
            "actualStartTime": 1657677116904, 
            "alternate": [FiberNode], 
            "child": [FiberNode], 
            "childLanes": 0, 
            "deletions": null, 
            "dependencies": null, 
            "elementType": "RCTView", 
            "flags": 4, 
            "index": 0, 
            "key": null, 
            "lanes": 0, 
            "memoizedProps": [Object], 
            "memoizedState": null, 
            "mode": 2, 
            "pendingProps": [Object], 
            "ref": [Object], 
            "return": [FiberNode], 
            "selfBaseDuration": 0, 
            "sibling": null, 
            "stateNode": [Circular], 
            "subtreeFlags": 1048577, 
            "tag": 5, 
            "treeBaseDuration": 2, 
            "type": "RCTView", 
            "updateQueue": null
        }, 
        
        "_nativeTag": 7, 
        "viewConfig": {
            "Commands": [Object], 
            "NativeProps": [Object], 
            "bubblingEventTypes": [Object], 
            "directEventTypes": [Object], 
            "uiViewClassName": "RCTView", 
            "validAttributes": [Object]
        }
        }, 
        
        "timeStamp": 1657677116946, 
        "touchHistory": {
            "indexOfSingleActiveTouch": 0, 
            "mostRecentTimeStamp": 47628960, 
            "numberActiveTouches": 0, 
            "touchBank": [[Object], 
            [Object]]
        }, 
        "type": undefined
        }